#version 450

struct Sphere{
    vec4 center;
    vec4 color;
};

layout (set = 0, binding = 0, rgba8) uniform writeonly image2D outImage;

layout (std430, set = 1, binding = 0) buffer sphereSSBO{
    Sphere spheres [];
};

layout(push_constant) uniform CameraObject {
    vec4 up;
    vec4 forward;
    vec4 right;
    vec4 position;
} camera;

layout (local_size_x = 8, local_size_y = 8) in;

struct Ray{
    vec3 origin;
    vec3 direction;
};

bool hit(Ray ray, Sphere sphere, out float tHit);

void main() {

    ivec2 screenPos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 screenSize = imageSize(outImage);

    float aspect = float(screenSize.x) / float(screenSize.y);

    float horizontalCoefficient = (float(screenPos.x) + 0.5) / float(screenSize.x) * 2.0 - 1.0; 
    horizontalCoefficient *= aspect;

    float verticalCoefficient   = 1.0 - (float(screenPos.y) + 0.5) / float(screenSize.y) * 2.0;

    Ray ray;
    ray.origin = camera.position.xyz;

    vec3 forward = camera.forward.xyz;
    vec3 right   = camera.right.xyz;
    vec3 up      = camera.up.xyz;

    vec3 rayDir = forward + horizontalCoefficient * right + verticalCoefficient * up;

    ray.direction = normalize(rayDir);

    vec3 pixelColor = vec3(0.0,0.0,0.0);

    int numSpheres = spheres.length();
    float minT = 99999999.0;
    for(int i=0; i<numSpheres; i++){
        
        Sphere s = spheres[i];
        
        float tHit;
        if(hit(ray, s, tHit) && tHit < minT){
            minT = min(tHit, minT);
            pixelColor = s.color.xyz;
        }
    }

    imageStore(outImage, screenPos, vec4(pixelColor, 1.0));
}

bool hit(Ray ray, Sphere sphere, out float tHit){
    vec3 oc = ray.origin - sphere.center.xyz;
    float a = dot(ray.direction, ray.direction);
    float b = 2.0 * dot(oc, ray.direction);
    float c = dot(oc, oc) - sphere.center.w * sphere.center.w;

    float discriminant = b*b - 4.0*a*c;
    if (discriminant < 0.0) return false;

    float sqrtDisc = sqrt(discriminant);
    float t0 = (-b - sqrtDisc) / (2.0 * a);
    float t1 = (-b + sqrtDisc) / (2.0 * a);

    t0 = max(t0, 0.0);
    t1 = max(t1, 0.0);

    tHit = min(t0, t1);
    return tHit > 0.0;
}