#version 450

struct Vertex{
    vec4 position;
    vec4 color;
    vec4 normal;
};

struct Triangle{
    ivec4 vertices; // 0, 1, 2, matIndex
};

struct Material{
    vec4 color;
    vec4 properties; // x: type
};

layout (set = 0, binding = 0, rgba8) uniform writeonly image2D outImage;

layout (set = 0, binding = 1, rgba8) uniform image2D accumImagePrev;
layout (set = 0, binding = 2, rgba8) uniform image2D accumImage;

layout (std430, set = 1, binding = 0) buffer materialSSBO{
    Material materials [];
};

layout (std430, set = 1, binding = 1) buffer vertexSSBO{
    Vertex vertices [];
};

layout (std430, set = 1, binding = 2) buffer triangleSSBO{
    Triangle triangles [];
};

layout(push_constant) uniform CameraObject {
    vec4 up;
    vec4 forward;
    vec4 right;
    vec4 position;
    vec4 utils;
} camera;

layout (local_size_x = 8, local_size_y = 8) in;

struct Ray{
    vec3 origin;
    vec3 direction;
};

struct HitRecord {
    vec3 p;
    vec3 normal;
    vec3 albedo;
    uint matIndex;
};

#define MAX_BOUNCES 10
#define RAYS_PER_PIXEL 32
#define SAMPLE_COUNT 100
#define PI 3.14159265

#define MATERIAL_LAMBERT 0
#define MATERIAL_LIGHT 1

int numMaterials = materials.length();
int numVertices = vertices.length();
int numTriangles = triangles.length();

uint rngState =
    uint(gl_GlobalInvocationID.x) * 1973u +
    uint(gl_GlobalInvocationID.y) * 9277u +
    uint(camera.utils.z) * 26699u +
    911u;

float rand(vec2 p)
{
    return fract(sin(dot(p.xy ,vec2(12.9898,78.233)) + camera.utils.x) * 43758.5453) * 0.5;
}

vec3 randomHemisphereDirection(vec3 normal, vec2 seed)
{
    vec2 seed1 = seed + vec2(camera.utils.x, camera.utils.x*1.3);
    vec2 seed2 = seed + vec2(camera.utils.x*2.1, camera.utils.x*3.7);

    float r1 = rand(seed1);
    float r2 = rand(seed2);

    float r = sqrt(r1);
    float theta = 2.0 * 3.14159265 * r2;

    float x = r * cos(theta);
    float y = r * sin(theta);
    float z = sqrt(1.0 - r*r);

vec3 localDir = vec3(x, y, z);

    vec3 up = abs(normal.z) < 0.999 ? vec3(0,0,1) : vec3(1,0,0);
    vec3 tangent = normalize(cross(up, normal));
    vec3 bitangent = cross(normal, tangent);

    return normalize(
        tangent * localDir.x +
        bitangent * localDir.y +
        normal * localDir.z
    );
}

vec3 randomSphere(vec2 seed)
{
    float u1 = rand(seed);
    float u2 = rand(seed + vec2(1.2345, 6.789));

    float z = 1.0 - 2.0 * u1;
    float phi = 2.0 * 3.14159265 * u2;

    float r = sqrt(max(0.0, 1.0 - z*z));

    float x = r * cos(phi);
    float y = r * sin(phi);

    return vec3(x, y, z);
}

bool hitTriangle(Ray ray, Triangle triangle, out float tHit, out float u, out float v){

    vec3 v0 = vertices[triangle.vertices.x].position.xyz;
    vec3 v1 = vertices[triangle.vertices.y].position.xyz;
    vec3 v2 = vertices[triangle.vertices.z].position.xyz;

    vec3 edge1 = v1 - v0;
    vec3 edge2 = v2 - v0;

    vec3 h = cross(ray.direction, edge2);
    float a = dot(edge1, h);

    if (abs(a) < 1e-6)
        return false;

    float f = 1.0 / a;
    vec3 s = ray.origin - v0;

    u = f * dot(s, h);
    if (u < 0.0 || u > 1.0)
        return false;

    vec3 q = cross(s, edge1);
    v = f * dot(ray.direction, q);
    if (v < 0.0 || u + v > 1.0)
        return false;

    tHit = f * dot(edge2, q);

    return tHit > 0.0;

}

vec3 lambertBRDF(vec3 albedo){
    return albedo / PI;
}

vec3 lambertThroughput(vec3 brdf, float cosTheta){
    
    float pdf = cosTheta / PI; //PDF for new dir

    return (brdf * cosTheta) / pdf;
}

bool hitScene(inout HitRecord hitRec, Ray ray){

    float minT = 1e30;
    bool hitSomething = false;

    for(int i=0; i<numTriangles; i++){
                
        float tHit;
        vec2 uv = vec2(0.0);

        Triangle tri = triangles[i];

        if(hitTriangle(ray, tri, tHit, uv.x, uv.y) && tHit < minT){
            minT = tHit;
            hitRec.p = ray.origin + ray.direction * tHit;
            hitRec.albedo = materials[tri.vertices.w].color.xyz;
            hitSomething = true;
            hitRec.normal = normalize(
                (1.0 - uv.x - uv.y) * vertices[tri.vertices.x].normal.xyz +
                uv.x * vertices[tri.vertices.y].normal.xyz +
                uv.y * vertices[tri.vertices.z].normal.xyz
            );
            hitRec.matIndex = tri.vertices.w;
        }
    }

    return hitSomething;
}

void buildONB(vec3 n, out vec3 u, out vec3 v, out vec3 w)
{
    w = normalize(n);
    vec3 a = abs(w.x) > 0.9 ? vec3(0,1,0) : vec3(1,0,0);
    v = normalize(cross(w, a));
    u = cross(w, v);
}

vec3 toWorld(vec3 localDir, vec3 normal)
{
    vec3 u, v, w;
    buildONB(normal, u, v, w);
    return normalize(localDir.x * u + localDir.y * v + localDir.z * w);
}

float random(inout uint state)
{
    state = state * 747796405u + 1u;
    uint word = ((state >> ((state >> 28) + 4)) ^ state) * 277803737u;
    word = (word >> 22) ^ word;
    return float(word) / 4294967295.0;
}

vec3 randomCosineDirection(inout uint rng)
{
    float r1 = random(rng);
    float r2 = random(rng);

    float phi = 2.0 * PI * r1;

    float x = cos(phi) * sqrt(r2);
    float y = sin(phi) * sqrt(r2);
    float z = sqrt(1.0 - r2);

    return vec3(x, y, z);
}

vec3 rayTraceColor(float horizontalCoefficient, float verticalCoefficient, vec2 screenPos, uint raysPerPixel){

    vec3 pixelColor = vec3(0.0,0.0,0.0);

    vec3 forward = camera.forward.xyz;
    vec3 right   = camera.right.xyz;
    vec3 up      = camera.up.xyz;

    float fov = radians(75.0);
    float fovScale = tan(fov * 0.5);

    for(int rayNum=0; rayNum<raysPerPixel; rayNum++){

        Ray ray;
        ray.origin = camera.position.xyz;

        vec3 rayDir = normalize(forward + horizontalCoefficient * fovScale * right + verticalCoefficient   * fovScale * up);

        vec2 jitter = vec2(rand(screenPos + vec2(camera.utils.x)), rand(screenPos + vec2(camera.utils.x * 0.3 + 1.0))) * 0.01;

        ray.direction = normalize(rayDir + vec3(jitter, 0.0));

        vec3 radiance = vec3(0.0);
        vec3 throughput = vec3(1.0);

    
        for(int bounce = 0; bounce < MAX_BOUNCES; bounce++){

            HitRecord rec;

            if(!hitScene(rec, ray))
                break;

            if(materials[rec.matIndex].properties.x == MATERIAL_LIGHT) //Add the emission since only lights emit
            {
                radiance += throughput * rec.albedo * materials[rec.matIndex].color.w;
                break;
            }

            if(dot(rec.normal, ray.direction) > 0.0){
                break;
            }

            vec3 localDir = randomCosineDirection(rngState); //Choose random direction in the normal's hemisphere (closer to normal)
            vec3 newDir = toWorld(localDir, rec.normal);

            float cosTheta = max(dot(rec.normal, newDir), 0.0); //Light new direction angle cosine
            vec3 brdf = lambertBRDF(rec.albedo);

            throughput *= lambertThroughput(brdf, cosTheta);

            ray.origin = rec.p + rec.normal * 0.0001;
            ray.direction = newDir;
            
        }

        
        pixelColor += radiance;
        
    }

    return pixelColor / raysPerPixel;
}

void main() {

    ivec2 screenPos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 screenSize = imageSize(outImage);

    float aspect = float(screenSize.x) / float(screenSize.y);

    float horizontalCoefficient = (float(screenPos.x) + 0.5) / float(screenSize.x) * 2.0 - 1.0; 
    horizontalCoefficient *= aspect;

    float verticalCoefficient   = 1.0 - (float(screenPos.y) + 0.5) / float(screenSize.y) * 2.0;
    
    vec3 accumulated;
    vec3 pixelColor;

    if(camera.utils.y != 0.0){

        pixelColor = rayTraceColor(horizontalCoefficient, verticalCoefficient, screenPos, RAYS_PER_PIXEL);
        vec4 oldColor = imageLoad(accumImagePrev, screenPos);
        accumulated = (oldColor.rgb * (camera.utils.z - 1) + pixelColor) / camera.utils.z;
    }else{
        
        pixelColor = rayTraceColor(horizontalCoefficient, verticalCoefficient, screenPos, 4);
        accumulated = pixelColor * 5.0;
    }

    imageStore(accumImage, screenPos, vec4(accumulated, 1.0));
    imageStore(outImage, screenPos, vec4(accumulated, 1.0));
}