#version 450

struct Particle {
    vec3 position;
};

layout(std140, binding = 0) readonly buffer ParticleSSBOIn {
   Particle particlesIn[4096];
};

layout(std140, binding = 1) buffer ParticleSSBOOut {
   Particle particlesOut[4096];
};

layout(push_constant) uniform bonusData{
    float time;
} bData;

layout (local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

void main() 
{
    uint index = gl_GlobalInvocationID.x;  

    Particle particleIn = particlesIn[index];

    particlesOut[index].position = vec3(particleIn.position.x, 
                                        particleIn.position.y, 
                                        particleIn.position.z) / 1.1;
}